---
title: "Final Project Report"
author: "Anna Delesalle (ajd16) & Owen Jin"
jupyter: julia-1.10
date: 2024-04-30

# YOU DO NOT NEED BOTH PDF AND DOCX.
# COMMENT OR DELETE THE ONE YOU DON"T WANT TO USE.
#
# Feel free to customize the look of your final document:
# https://quarto.org/docs/reference/formats/pdf.html
# https://quarto.org/docs/reference/formats/docx.html

format: 
    pdf:
        documentclass: article
        fontsize: 11pt
        geometry:
            - margin=1in  
        number-sections: true
        code-line-numbers: true
    # docx: 
    #    toc: true
    #    fig-format: png
    #    number-sections: true
    #    code-line-numbers: true

date-format: "ddd., MMM. D"

# See Quarto docs: https://quarto.org/docs/authoring/footnotes-and-citations.html
# you can export your references from Zotero, EndNote, or other reference managers
# from Zotero you"ll need https://retorque.re/zotero-better-bibtex/
references: references.bib

# recommended, but not required
# you will need jupyter-cache installed
execute: 
  cache: true
---

# Introduction

## Problem Statement
Elevating a house is very costly and is the reason why this decision is put off into the future. With the help of grants, buildings are able to be elevated as needed in a proactive timeframe which prevents further damages.

Federal grants have been a crucial form of assistance for households living in areas prone to flooding, but there is lacking research into how these grants impact the cost-benefit ratio and how these funds are allocated.

After demonstrating the significance of an elevation construction grant to a homeowner or community, we found that these grants are more often allocated for wealthier homes/businesses. Many of these programs are required to go through larger communities before getting allotted to individuals which makes it even harder for marginalized communities/families to receive this form of funding.

## Selected Feature
We added the FEMA FMA grant as a percentage to the SOW function in the source code. We decided to include this grant as 0%, 75%, and 90% because the grant is not attributed to everyone and the other values are the two amounts that are most commonly distributed. Providing multiple different grant values allows us to compare various SOWs and the effectiveness of the FEMA grant to prevent flood induced damages.

In addition to the FEMA FMA grant we chose to incorporate the HMGP grant which comes into play once the flood damages have been made. This grant is also distributed at a rate of 75% however it will have different effects on the SOW because it is not proactive in nature unlike FEMA FMA.

With these two additions to the model we are able to compare the NVPs for different SOWs which include different floods and different levels of grants.

# Literature Review
Flood Mitigation Assistance (FMA) is a grant program led by the Federal Emergency Management Agency (FEMA) in order to limit the damages that come with the increasing severity of floods in the US. The grants are not handed out to individual homeowners but rather they are allotted to authorities and communities on the local scale. These groups are then free to distribute their grants as they see fit. (https://www.epa.gov/sites/default/files/2015-10/documents/fma.pdf)

This article touches on the accessibility of FEMA grants in the US and the help that they bring to communities and home owners around the country. In this article the authors bring up their concern for the future FEMA programs that are in the works of being implemented given the current implementation of the existing FEMA grant programs.
(https://mdpi-res.com/sustainability/sustainability-12-10013/article_deploy/sustainability-12-10013.pdf?version=1606799504)

Similarly, this article focuses on the FEMA’s Hazard Mitigation Assistance Program (HMAP) and its poor implementation. The author suggests that these grants become better used and more widespread across the country in order for them to be effective.
 
This is where our model comes into play, by incorporating FEMA grants into the original model we attempt to gauge the effectiveness of having flood mitigation grants. By generating many SOWs with different circumstances and levels of grants we hope to better understand the impact that FEMA FMA and HMGP grants can have on house elevation NPV calculations.


# Methodology
```{julia}
using CSV
using DataFrames
using DataFramesMeta
using Distributions
using LaTeXStrings
using Metaheuristics
using Plots
using Random
using Unitful

Plots.default(; margin=5Plots.mm)
```

```{julia}
using Revise
using HouseElevation
```

```{julia}
#| output: false
house = let
    haz_fl_dept = CSV.read("data/haz_fl_dept.csv", DataFrame) # read in the file
    desc = "one story, no basement, Contents"
    row = @rsubset(haz_fl_dept, :Source == "USACE - Galveston", :Description == desc)[1, :] # select the row I want
    area = 2001u"ft^2"
    height_above_gauge = 10u"ft"
    House(row; area=area, height_above_gauge=height_above_gauge, value_usd=363_000)
end

p = ModelParams(; house=house, years=2024:2083)
```

```{julia}
#| output: false
slr_scenarios = let
    df = CSV.read("data/slr_oddo.csv", DataFrame)
    [Oddo17SLR(a, b, c, tstar, cstar) for (a, b, c, tstar, cstar) in eachrow(df)]
end

function draw_surge_distribution()
    μ = rand(Normal(5, 1))
    σ = rand(Exponential(1.25))
    ξ = rand(Normal(0.1, 0.05))
    return GeneralizedExtremeValue(μ, σ, ξ)
end

function draw_discount_rate()
    return rand(Normal(0.05, 0.03))
end

function draw_damages_grant()
    rand([0,0,.75,.75,.9])
end

function draw_elevation_grant()
    rand([0,0,.75,.75,.9])
end

function draw_sow()
    slr = rand(slr_scenarios)
    surge_params = draw_surge_distribution()
    discount = draw_discount_rate()
    grant = draw_elevation_grant()
    damages_grant = draw_damages_grant()
    return SOW(slr, surge_params, discount, grant, damages_grant)
end

```

```{julia}
#| output: false
Random.seed!(421521)
N_SOW = 10_000
N_SOW_opt = 10 # to start
sows = [draw_sow() for _ in 1:N_SOW]
sows_opt = first(sows, N_SOW_opt)
```

```{julia}
bounds = boxconstraints(; lb=[0.0], ub=[14.0])
```

```{julia}
function objective_function(Δh::Vector{Float64})
    a = Action(Δh[1])
    npvs = [run_sim(a, sow, p) for sow in sows_opt]
    return -mean(npvs)
end
```

```{julia}
result = optimize(objective_function, bounds)
```

```{julia}
minimum(result)
```

```{julia}
minimizer(result)
```

```{julia}
N_SOW_opt = 100
sows_opt = first(sows, N_SOW_opt)
```

```{julia}
options = Options(; time_limit=180.0, f_tol_rel=10.0)
```

```{julia}
algorithm = ECA(; options=options)
```

```{julia}
Random.seed!(421521)
result = optimize(objective_function, bounds, algorithm)
```

```{julia}
display(minimum(result))
display(minimizer(result))
```


## Implementation

In methodology section above, a couple of details to highlight:
- new functions draw_damages_grant() and draw_elevations_grant()
    - these include an array representing possible scenarios for grants
    - 0 means no grant is given, .75 is a grant covering 75% of costs, and .9 is 90% of costs
- those functions will be called in draw_sows()

We included two additional elements in SOW
struct SOW{T<:Real, E<:Real, S<:Real}
    slr::Oddo17SLR # the parameters of sea-level rise
    surge_dist::Distributions.UnivariateDistribution # the distribution of storm surge
    discount_rate::T # the discount rate, as a percentage (e.g., 2% is 0.02)
    grant::E # The grant amount as a percentage of what the government will pay for the elevation.
    damages_grant::S # The grant amount as a percentage of what the government will pay for the damages.
end

In the run_sim function, construction_cost will now account for the potential construction grant
ead_npv also accounts for potential grants to help offset damages
function run_sim(a::Action, sow::SOW, p::ModelParams)
    construction_cost = elevation_cost(p.house, a.Δh_ft, sow.grant)
    .
    .
    .
    ead_npv = sum(eads .* discount_fracs) * (1 - sow.damages_grant)
    return -(ead_npv + construction_cost)
end


## Validation

We conducted a sensitivity analysis to assess the robustness of the implemented feature across a range of scenarios. This involved varying parameters such as elevation levels and grant amounts to observe their impact on the net present value (NPV) of the decision-support tool. By systematically exploring different combinations of parameters, we gained insights into how changes in the feature inputs affect the output.
```{julia}
#| output: false
elevations_try = 0:0.5:14
actions_try = Action.(elevations_try)

N_more = 500
npvs_opt = [mean([run_sim(a, sow, p) for sow in sows_opt]) for a in actions_try]
npvs_moore = [
    mean([run_sim(a, sow, p) for sow in first(sows, N_more)]) for a in actions_try
]
```

We visualized the sensitivity analysis results to provide insights into the relationship between elevation levels and NPV.

Overall, the optimization accurately maximizes the blue curve. There is a slight difference between the blue and red lines, which shows how variability in the SOWs can impact NPVs.
```{julia}
plot(
    elevations_try,
    npvs_opt ./ 1000;
    xlabel="Elevation [ft]",
    ylabel="NPV [1000 USD]",
    label="First $(N_SOW_opt) SOWs",
    marker=:circle,
)
plot!(elevations_try, npvs_moore ./ 1000; label="First $(N_more) SOWs", marker=:circle)
vline!([minimizer(result)]; label="Optimal", linestyle=:dash)
```

# Results

Present the results obtained from the enhanced decision-support tool.
Use tables, figures, and visualizations to clearly communicate the outcomes.
Provide sufficient detail to demonstrate how the implemented feature addresses the problem statement.
Use the `#| output: false` and/or `#| echo: false` tags to hide code output and code cells in the final report except where showing the output (e.g.g, a plot) or the code (e.g., how you are sampling SOWs) adds value to the discussion.
You may have multiple subsections of results, which you can create using `##`.

The results obtained from our enhanced decision-support tool are presented below. The table provides a comprehensive overview of the outcomes, illustrating the relationship between elevation grants, damage grants, minimum NPV values, and elevation heights.

```{julia}
using DataFrames

column1_data = ["[0,0,0,0,0] (0)", "[0,0,0,0,0] (0)", "[0,0,0,0,0] (0)", "[0,0,0,0,.75] (.15)","[0,0,0,.75,.75] (.3)","[0,0,.75,.75,.9] (.48)","[0,0,.75,.75,.9] (.48)","[0,0,.75,.75,.9] (.48)","[.75,.75,.75,.75,.9] (.78)","[.75,.75,.75,.75,.9] (.78)"]
column2_data = ["[0,0,0,0,0] (0)", "[0,0,.75,.75,.9] (.48)", "[.75,.75,.75,.75,.9] (.78)", "[0,0,.75,.75,.9] (.48)","[0,0,.75,.75,.9] (.48)","[0,0,0,0,0] (0)","[0,0,0,.75,.75] (.3)","[0,0,.75,.75,.9] (.48)","[0,0,0,0,0] (0)","[.75,.75,.75,.75,.9] (.78)"]
column3_data = [229184, 208427, 198616, 179428,135928,130303,119106,115628,61237.6,48050.8]
column4_data = [8.80329,8.5,7.67433,8.5,8.5,10.9463,8.65081,8.5,13.8813,8.5] 
```

```{julia}
df = DataFrame(Elevation_Grant_Array = column1_data,
               Damage_Grant_Array = column2_data,
               Minimum_NPV = column3_data,
               Elevation = column4_data)

println(df)
```

The table reveals several key insights:
Elevation Grant Array and Damage Grant Array:  Scenarios with higher construction and damage grants tend to yield lower NPV values, with elevation grants having a more significant impact overall. This suggests that the upfront cost plays a crucial role in adaptation decisions. The data underscores the importance of financial assistance in alleviating the economic burden on homeowners.
Minimum NPV: The minimum NPV values range from $48,050.80 to $229,184, reflecting the economic implications of different adaptation strategies. Scenarios with higher construction and damage grants generally result in lower NPV values, indicating more favorable investment outcomes.
Elevation Height:  Elevation heights exhibit variability across scenarios, ranging from 7.67433 feet to 13.8813 feet. Damage grants appear to be inversely correlated with elevation height. Additionally, multiple scenarios converge at an elevation height of 8.5 feet, suggesting that this height may be particularly optimal for the homeowner under consideration.


# Conclusions

## Discussion

Our study unveils significant insights for climate risk management. We identify a close relationship between higher construction grants and lower (less negative) NPV values, highlighting the critical role of financial assistance in enhancing the economic viability of flood mitigation measures. Furthermore, we observe a correlation between higher damage grants and lower elevation heights. Interestingly, multiple scenarios for our house converge at 8.5 feet elevation height. These findings contribute to advancing climate risk assessment methodologies by emphasizing the importance of integrating financial incentives into adaptation planning and informing equitable resilience strategies.

One element that we did not include in this model is the distribution of the grants among different races or socio-economic backgrounds. Not all individuals/homeowners will be treated equally when it comes to allocating the grants and this is something that should be taken into account in the model for future work. 


## Conclusions

As summarized in the table above, the highest NPV is achieved when both grants are awarded, meaning the initial cost of the house elevation is reduced by either 75% or 90% and any damages that occur with a flood are covered at a rate of 75% in addition to the house elevation. 
Our findings reinforce the points made in the articles we cited in the literature review stating that FEMA grants are important to flood-prone areas in helping alleviate the cost of damages but that these are not widespread enough. The results from our model clearly demonstrate the effectiveness of having grants, either one or both, in order to optimize a Net Present Value.


# References

Civic Plus. n.d. “Home Elevation Program | Nassau Bay, TX.” City of Nassau Bay. Accessed April 30, 2024. https://www.nassaubay.com/591/Home-Elevation-Program.
Dodds, Luke. 2022. “Mitigation Saves? High Discount Rates Undermine FEMA’s Efforts to Promote National Resilience.” 18. https://www.proquest.com/docview/2827023388/fulltext/241D095D1CDB471EPQ/1?accountid=7064&sourcetype=Scholarly%20Journals&parentSessionId=7yVKZdbU2DGR%2FY%2BUtwE8XXeW0n5Pu7OdWh4nccHG%2FnI%3D.
“Flood Mitigation Assistance (FMA) Program.” n.d. US EPA. Accessed April 30, 2024. https://www.epa.gov/sites/default/files/2015-10/documents/fma.pdf.
Frimpong, Eugene, Gregory Howard, and Jamie Kruse. n.d. “Homeowner Preference for Household-level Flood Mitigation in US: Analysis of a Discrete Choice Experiment.” Accessed April 30, 2024. https://www.cambridge.org/core/services/aop-cambridge-core/content/view/9EAF557316CA984837F2B6F56590AF9B/S1074070822000050a.pdf/div-class-title-homeowner-preference-for-household-level-flood-mitigation-in-us-analysis-of-a-discrete-choice-experiment-div.pdf.
“Home Elevation Grants & Private Financing | Flood Insurance Guidelines.” 2021. Planet Three Elevation. https://p3elevation.com/home-elevation-grants-financing-insurance/.
Smith, Gavin, and Olivia Vila. 2020. “A National Evaluation of State and Territory Roles in Hazard Mitigation: Building Local Capacity to Implement FEMA Hazard Mitigation Assistance Grants.” MDPI, (November). https://mdpi-res.com/sustainability/sustainability-12-10013/article_deploy/sustainability-12-10013.pdf?version=1606799504.
:::{#refs}
:::